# Fake news Classifier

In [84]:
# import required Libraries
import pandas as pd
import numpy as np

In [85]:
# Read the csv file 
df=pd.read_csv('C:/Users/haiva/Downloads/fake-news/train.csv')


In [86]:
#print first five lines of data
df.head(5)

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [87]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [88]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [89]:
## Get the Dependent features
y=df['label']

In [90]:
#delete null values of data
df=df.dropna()

In [91]:
# make a copy of original data 
messages=df.copy()

In [92]:
# Reset index of the data because of deeleted null vaues of data
messages.reset_index(inplace=True)

In [93]:
messages.head(5)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

# Preprocess of The data

In [94]:
# basic cleaning Required i.e if there is any Stop words and some words in capital letter
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [95]:
corpus[3]

'civilian kill singl us airstrik identifi'

# make vectrization using CountVectRizer

In [96]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [97]:
## Applying Countvectorizer
# Creating the Bag of Words model by taking max 5000 Features
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [98]:
y=messages['label']

# Spliting of the Data Set 

In [105]:
## Divide the dataset into Train and Test into 80% ,20%
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [106]:
from sklearn import metrics
import numpy as np
import itertools

# Apply Naive Bays 

In [107]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [108]:
#FIt the training data  and make prediction on test data
from sklearn.metrics import accuracy_score, confusion_matrix
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)

# Print the Accuracy and confusion matrix of model

In [109]:
score=accuracy_score(y_test,pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 90.16%


In [110]:
confusion_matrix(y_test,pred)

array([[1823,  217],
       [ 143, 1474]], dtype=int64)

# Apply Decision tree Classifier 

In [111]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)

In [115]:
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [116]:
score=accuracy_score(y_test,pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 92.48%


In [117]:
confusion_matrix(y_test,pred)

array([[1881,  159],
       [ 116, 1501]], dtype=int64)

# Make Vectriztion Using TFIDF-vectrizer and make predictions

In [119]:
## TFidf Vectorizer
# Creating the Bag of Words model by taking max 5000 Features
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_v=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=tfidf_v.fit_transform(corpus).toarray()

In [120]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

# Apply Navie-bays make predictions and Print acuuracy and confusion matrix 

In [121]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)

In [122]:
score=accuracy_score(y_test,pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 88.1%


In [ ]:
Apply Decisiontree Classifier make predictions and print 

In [123]:
confusion_matrix(y_test,pred)

array([[3190,  199],
       [ 519, 2127]], dtype=int64)

# Apply Decision-tree make predictions and Print acuuracy and confusion matrix

In [124]:
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [125]:
score=accuracy_score(y_test,pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 91.15%


In [126]:
confusion_matrix(y_test,pred)

array([[3105,  284],
       [ 250, 2396]], dtype=int64)